### PR TITLE
Add custom admin action csv and make updates for 20.XX release

### PR DESCRIPTION
**Pull request by dmhdev**
Closes # 16.

Changes proposed in this PR:

- Add custom admin action to export waiting list entries as csv.
- Add unit tests for custom admin action in pinax/waitinglist/tests/tests.py
  - Tested on Django 1.11 with Python 2.7, 3.4, 3.5, 3.6 and Django 2.0 with Python 3.4, 3.5, 3.6, 3.7

### CODE REVIEW

**Comment by KatherineMichel** [comment]
FYI, I had to order a new computer. Old one is EoL. I'll review/merge this as soon as I can and include in new release happening later this month. I'm thrilled I'll be able to close a longstanding issue.

**Comment by dmhdev** [comment]
Sounds great

**Comment by KatherineMichel** [comment]
@vdaynm Finally have new computer up and running and reviewed this. I had a few strange errors from Python 2.7 and 3.6 that I wouldn't have had with my old computer, so I went ahead and made the changes for the upcoming release, so that I could properly fix the the errors based on new versions. Hope you don't mind. Everything looked good, except I got an error that said: "pinax/waitinglist/admin.py:40:13: F841 local variable 'row' is assigned to but never used"... not sure yet if this is something that should be ignored, or a legit error. Do you know?
Screen Shot 2020-05-14 at 7 40 38 PM

**Comment by KatherineMichel** [comment]
I'm going to call it good. Thank you for doing this!

**Comment by dmhdev** [comment]
Hi Katherine, alright then glad I could contribute. The update tested correctly on my end.

**Pull request merged**
